### ISSUE TITLE
Vite configFile is not a thing anymore (or ever was)

### ISSUE THREAD

**Issue by airtonix** [nxext/nx-extensions#629]
**Describe the bug**
my apps vite.config.ts never gets used. 

- https://github.com/airtonix/vscode-graphiql/issues/1
- https://github.com/airtonix/vscode-graphiql/tree/1-nxextvite-never-uses-viteconfigts

**To Reproduce**
- clone
- have asdf, asdf-pnpm asdf-nodejs, asdf-just
- pnpm i
- put some console logs in the `@nxext/vite/src/executors/build/executor.ts` @ line 49 : `            devkit_1.logger.info(buildConfig)
`
- pnpx nx build graphiql-webview
- see that the resulting config never merges with project config
- see that build fails because it can't resolve the tsconfig paths.

![image](https://user-images.githubusercontent.com/61225/163898514-0a109d84-b1af-4d03-aa38-ae7f508e6d86.png)

**Expected behavior**
that things should work.

**Additional context**
???

**Comment by airtonix** [comment]
not sure what the intention of seting `configFile` is, I can only assume that you thought setting this would be equivilant to `vite --config=./path-to-config-file.ts`

**Comment by Jordan-Hall** [comment]
I'll take a look at this. It was meant to merge the config file. If thats not working then. we will manually read the file and merge it ourselves.

**Comment by DominikPieper** [comment]
@Jordan-Hall it's no problem with the config merge. I tried right now, it's again the problem with transitive deps. The open PR should fix this as well :-)

**Comment by DominikPieper** [comment]
@airtonix could you try the latest version?

**Comment by airtonix** [comment]
I'll try it out now

**Comment by airtonix** [comment]
nope, still doesn't respect my vite.config.ts ... 

i have in there something like: 

```

    build: {
      emptyOutDir: false,
      outDir: 'dist/graphiql-extension'
    }
```

and it refuses to write the output there instead it writes it to `../../dist/apps/graphiql-webview/`

**Comment by Jordan-Hall** [comment]
> and it refuses to write the output there instead it writes it to ../../dist/apps/graphiql-webview/

Thats working as expected. NX has a strict folder structure we are adhering too.

**Comment by DominikPieper** [comment]
Yes that’s the reason. Nx defines the output structure and it’s needed for various mechanisms to work like the cache

**Comment by airtonix** [comment]
oh well that doesn't work for vscode extensions sorry. guess I'll have to fork your project

**Comment by DominikPieper** [comment]
Maybe a plain Vite project is better than? If that don’t fit with the structure of Nx, maybe Nx isn’t the best tool for the job

**Comment by Jordan-Hall** [comment]
Agree, if you change the output, then you will loose everything but schematic for NX. You are able to change the folder structure but for NX itself... what plugin are you using and why do you need to change it.

**Comment by Jordan-Hall** [comment]
Reopening the ticket as more talk internally about this and see what would break from NX side. Already been talks about less reliant on NX while keeping benefits such as schematics and nx cloud.

@airtonix 

1. What's the use case to change the path?
2. Is this a global change of dist to a flat structure or per app

**Comment by DominikPieper** [comment]
@airtonix I added the possibility to set the outputDir through the project.json. It's not the vite config but through this it's more the nx dir to set something global like this. Would that work for you?
